function v = total_v(t, x, f, h, delta, orientation, pos, t0, dt)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %% TOTAL_V
    % Computes the total velocity generated by an ensemble of
    % regularized Stokeslets.
    %
    % This function evaluates the velocity at position x and time t by summing
    % the contributions of all Stokeslets whose positions and orientations are
    % stored in the input cell arrays. Each individual contribution is computed
    % through the function Reg_Stokeslet_velocity_near_wall.
    %
    % INPUT
    % - t           :   Time at which the total velocity is evaluated at.
    % - x           :   3 x 1 position vector at which the velocity is computed at.
    % - f           :   Scalar strength of the Stokeslets.
    % - h           :   Height of the regularized Stokeslets.
    % - delta       :   Regularization radius of the Stokeslets.
    % - orientation :   Cell array containing the orientation history of the
    %                   Stokeslet force for each actuator.
    % - pos         :   Cell array containing the position history of the
    %                   Stokeslets for each actuator.
    % - t0          :   Initial time associated with the stored trajectories.
    % - dt          :   Time step between two consecutive stored frames.
    %
    % OUTPUT
    % - v           :   3 x 1 velocity vector at position x and time t produced
    %                   by the ensemble of Stokeslets.
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    % Basic input checks
    if isempty(pos) || isempty(orientation)
        error('Error: pos and orientation must be non-empty cell arrays.');
    end
    
    if ~iscell(pos) || ~iscell(orientation)
        error('Error: pos and orientation must be cell arrays.');
    end
    
    if numel(pos) ~= numel(orientation)
        error('Error: pos and orientation must contain the same number of elements.');
    end
    
    if numel(x) ~= 3
        error('Error: x must be a 3-component position vector.');
    end
    
    % Convert the physical time t into the closest discrete time index
    idx = round((t - t0) / dt) + 1;
    
    % Clamp the index to the available time range
    idx = max(1, min(idx, size(pos{1}, 2)));
    
    % Initialize the total velocity
    v = [0; 0; 0];
    
    % Sum the contribution of each Stokeslet
    for i = 1:numel(pos)
    
        % Extract the current position and orientation of the i-th actuator
        p_curr = pos{i}(:, idx);
        o_curr = orientation{i}(idx);
    
        % Skip invalid entries
        if isnan(o_curr) || any(isnan(p_curr))
            continue;
        end
    
        % Direction of the force (assumed to be horizontal)
        % associated with the current actuator
        f_dir = [0;cos(o_curr);sin(o_curr)] * f;
    
        % Add the contribution of the current regularised Stokeslet
        v = v + Reg_Stokeslet_velocity_near_wall([x(1); x(2:3) - p_curr(2:3)], ...
            f_dir, h, delta);
    end
    
    % Prevent negative vertical velocity close to the lower boundary
    if x(1) <= 10^-5 && v(1) < 0
        v = [0;0;0];
    end



end